variable "automated_snapshot_start_hour" {}
variable "cluster_name" {}
variable "dedicated_master_count" {}
variable "dedicated_master_enabled" {}
variable "dedicated_master_type" {}
variable "elasticsearch_name" {}
variable "elasticsearch_version" {}
variable "instance_count" {}
variable "instance_type" {}
variable "k8s_environment" {}
variable "kms_key_name" {}
variable "solution_abbreviation" {}
variable "tenant_id" {}
variable "volume_size" {}
variable "zone_awareness_enabled" {}
